"""add urls

Revision ID: c3d8c12a4c8a
Revises: 5543d61ba283
Create Date: 2023-05-09 22:25:19.572340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d8c12a4c8a'
down_revision = '5543d61ba283'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
